name: flake8

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flake8:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Analysing the code with flake8
        # E124,E127,E128 ignore all visual indent errors
        # E701 ignore multi-statement per line (because of 'name: type' error)
        # E731 allow lambdas
        run: |
          flake8 $(git ls-files '*.py') --max-line-length=120 --ignore=E124,E127,E128,E701,E731
